/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.3.1
 * Wed, 31 May 2023 06:04:24 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables/constants used by puzzles' functions

var LIST_NONE = '<none>';

var _pGlob = {};

_pGlob.objCache = {};
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

var PL = {};
// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    var _initGlob = {};
    _initGlob.percentage = 0;
    _initGlob.output = {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        }
    }

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    // utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'CONTAINER' && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'CONTAINER') {
        if (appInstance !== null) {
            elem = appInstance.container;
        } else if (typeof _initGlob !== 'undefined') {
            // if we are on the initialization stage, we still can have access
            // to the container element
            var id = _initGlob.container;
            if (isParent) {
                elem = parent.document.getElementById(id);
            } else {
                elem = document.getElementById(id);
            }
        }
    } else if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}

// setCSSRuleStyle puzzle
function setCSSRuleStyle(prop, value, id, isParent, mediaRule) {
    var styles = (isParent) ? parent.document.styleSheets : document.styleSheets;
    for (var i = 0; i < styles.length; i++) {
        /**
         * workaround for "DOMException: Failed to read the 'cssRules' property
         * from 'CSSStyleSheet': Cannot access rules"
         */
        try { var cssRules = styles[i].cssRules; }
        catch (e) { continue; }

        for (var j = 0; j < cssRules.length; j++) {
            var cssRule = cssRules[j];
            if (!mediaRule && cssRule.selectorText == id)
                cssRule.style[prop] = value;
            else if (mediaRule && cssRule.media && cssRule.media.mediaText == mediaRule) {
                var cssRulesMedia = cssRule.cssRules;
                for (var k = 0; k < cssRulesMedia.length; k++) {
                    if (cssRulesMedia[k].selectorText == id)
                        cssRulesMedia[k].style[prop] = value;
                }
            }
        }
    }
}



// initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = false;
_initGlob.output.initOptions.useFullscreen = false;

setCSSRuleStyle('backgroundImage', 'url("manitou.png")', '.v3d-simple-preloader-logo', false, '');

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["stopnotclicked"] = stopnotclicked;
this.procedures["rothorclicked"] = rothorclicked2;
this.procedures["rothornotclicked"] = rothornotclicked;
this.procedures["rotantihorclicked"] = rotantihorclicked2;
this.procedures["rotantihornotclicked"] = rotantihornotclicked;
this.procedures["stopclicked"] = stopclicked2;

var stopclicked, rothorclicked, rotantihorclicked;

/**
 * Get a scene that contains the root of the given action.
 */
function getSceneByAction(action) {
    var root = action.getRoot();
    var scene = root.type == "Scene" ? root : null;
    root.traverseAncestors(function(ancObj) {
        if (ancObj.type == "Scene") {
            scene = ancObj;
        }
    });
    return scene;
}

/**
 * Get the current scene's framerate.
 */
function getSceneAnimFrameRate(scene) {
    if (scene && 'animFrameRate' in scene.userData) {
        return scene.userData.animFrameRate;
    }
    return 24;
}

// getAnimationFrame puzzle
function getAnimationFrame(animName) {
    if (!animName)
        return;
    var action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
    if (action) {
        var scene = getSceneByAction(action);
        var frameRate = getSceneAnimFrameRate(scene);
        return action.time * frameRate;
    } else {
        return;
    }
}

// utility function envoked by almost all V3D-specific puzzles
// filter off some non-mesh types
function notIgnoredObj(obj) {
    return obj.type !== 'AmbientLight' &&
           obj.name !== '' &&
           !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
           !obj.isAuxClippingMesh;
}


// utility function envoked by almost all V3D-specific puzzles
// find first occurence of the object by its name
function getObjectByName(objName) {
    var objFound;
    var runTime = _pGlob !== undefined;
    objFound = runTime ? _pGlob.objCache[objName] : null;

    if (objFound && objFound.name === objName)
        return objFound;

    if (appInstance.scene) {
        appInstance.scene.traverse(function(obj) {
            if (!objFound && notIgnoredObj(obj) && (obj.name == objName)) {
                objFound = obj;
                if (runTime) {
                    _pGlob.objCache[objName] = objFound;
                }
            }
        });
    }
    return objFound;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects on the scene
function getAllObjectNames() {
    var objNameList = [];
    appInstance.scene.traverse(function(obj) {
        if (notIgnoredObj(obj))
            objNameList.push(obj.name)
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects which belong to the group
function getObjectNamesByGroupName(targetGroupName) {
    var objNameList = [];
    appInstance.scene.traverse(function(obj){
        if (notIgnoredObj(obj)) {
            var groupNames = obj.groupNames;
            if (!groupNames)
                return;
            for (var i = 0; i < groupNames.length; i++) {
                var groupName = groupNames[i];
                if (groupName == targetGroupName) {
                    objNameList.push(obj.name);
                }
            }
        }
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// process object input, which can be either single obj or array of objects, or a group
function retrieveObjectNames(objNames) {
    var acc = [];
    retrieveObjectNamesAcc(objNames, acc);
    return acc.filter(function(name) {
        return name;
    });
}

function retrieveObjectNamesAcc(currObjNames, acc) {
    if (typeof currObjNames == "string") {
        acc.push(currObjNames);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "GROUP") {
        var newObj = getObjectNamesByGroupName(currObjNames[1]);
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "ALL_OBJECTS") {
        var newObj = getAllObjectNames();
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames)) {
        for (var i = 0; i < currObjNames.length; i++)
            retrieveObjectNamesAcc(currObjNames[i], acc);
    }
}

// assignMaterial puzzle
function assignMat(objSelector, matName) {
    var objNames = retrieveObjectNames(objSelector);
    if (!matName)
        return;
    var mat = v3d.SceneUtils.getMaterialByName(appInstance, matName);
    if (!mat)
        return;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        if (!objName)
            continue;
        var obj = getObjectByName(objName);
        if (obj) {
            var firstSubmesh = obj.resolveMultiMaterial()[0];
            firstSubmesh.material = mat;
        }
    }
}

// isAnimationPlaying puzzle
function isAnimationPlaying(animations) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];
    for (let i = 0; i < animations.length; i++) {
        const animName = animations[i];
        if (!animName)
            continue;
        const action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (action && action.isRunning())
            return true;
    }
    return false;
}

// show and hide puzzles
function changeVis(objSelector, bool) {
    var objNames = retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = getObjectByName(objName);
        if (!obj)
            continue;
        obj.visible = bool;
        obj.resolveMultiMaterial().forEach(function(objR) {
            objR.visible = bool;
        });
    }
}

// everyFrame puzzle
function registerEveryFrame(callback) {
    if (typeof callback == 'function') {
        appInstance.renderCallbacks.push(callback);
        if (PL.editorRenderCallbacks)
            PL.editorRenderCallbacks.push([appInstance, callback]);
    }
}

// callJSFunction puzzle
function getJSFunction(funcName) {
    var jsFunc = appInstance.ExternalInterface[funcName];
    if (typeof jsFunc == "function")
        return jsFunc;
    else
        return function() {};
}

function _checkListenersSame(target0, type0, listener0, optionsOrUseCapture0,
        target1, type1, listener1, optionsOrUseCapture1) {
    const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
            ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
    const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
            ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
    return target0 === target1 && type0 === type1 && listener0 === listener1
            && capture0 === capture1;
}

/**
 * Add the specified event listener to the specified target. This function also
 * stores listener data for easier disposing.
 */
function bindListener(target, type, listener, optionsOrUseCapture) {
    const alreadyExists = _pGlob.eventListeners.some(elem => {
        return _checkListenersSame(elem.target, elem.type, elem.listener,
                elem.optionsOrUseCapture, target, type, listener,
                optionsOrUseCapture);
    });

    if (!alreadyExists) {
        target.addEventListener(type, listener, optionsOrUseCapture);
        _pGlob.eventListeners.push({ target, type, listener, optionsOrUseCapture });
    }
}

// utility function used by the whenClicked, whenHovered and whenDraggedOver puzzles
function initObjectPicking(callback, eventType, mouseDownUseTouchStart, mouseButtons) {

    var elem = appInstance.renderer.domElement;
    bindListener(elem, eventType, pickListener);

    if (eventType == 'mousedown') {

        var touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
        bindListener(elem, touchEventName, pickListener);

    } else if (eventType == 'dblclick') {

        var prevTapTime = 0;

        function doubleTapCallback(event) {

            var now = new Date().getTime();
            var timesince = now - prevTapTime;

            if (timesince < 600 && timesince > 0) {

                pickListener(event);
                prevTapTime = 0;
                return;

            }

            prevTapTime = new Date().getTime();
        }

        var touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
        bindListener(elem, touchEventName, doubleTapCallback);
    }

    var raycaster = new v3d.Raycaster();

    function pickListener(event) {

        // to handle unload in loadScene puzzle
        if (!appInstance.getCamera())
            return;

        event.preventDefault();

        var xNorm = 0, yNorm = 0;
        if (event instanceof MouseEvent) {
            if (mouseButtons && mouseButtons.indexOf(event.button) == -1)
                return;
            xNorm = event.offsetX / elem.clientWidth;
            yNorm = event.offsetY / elem.clientHeight;
        } else if (event instanceof TouchEvent) {
            var rect = elem.getBoundingClientRect();
            xNorm = (event.changedTouches[0].clientX - rect.left) / rect.width;
            yNorm = (event.changedTouches[0].clientY - rect.top) / rect.height;
        }

        _pGlob.screenCoords.x = xNorm * 2 - 1;
        _pGlob.screenCoords.y = -yNorm * 2 + 1;
        raycaster.setFromCamera(_pGlob.screenCoords, appInstance.getCamera(true));
        var objList = [];
        appInstance.scene.traverse(function(obj){objList.push(obj);});
        var intersects = raycaster.intersectObjects(objList, false);
        callback(intersects, event);
    }
}

function objectsIncludeObj(objNames, testedObjName) {
    if (!testedObjName) return false;

    for (var i = 0; i < objNames.length; i++) {
        if (testedObjName == objNames[i]) {
            return true;
        } else {
            // also check children which are auto-generated for multi-material objects
            var obj = getObjectByName(objNames[i]);
            if (obj && obj.type == "Group") {
                for (var j = 0; j < obj.children.length; j++) {
                    if (testedObjName == obj.children[j].name) {
                        return true;
                    }
                }
            }
        }
    }
    return false;
}

// utility function used by the whenClicked, whenHovered, whenDraggedOver, and raycast puzzles
function getPickedObjectName(obj) {
    // auto-generated from a multi-material object, use parent name instead
    if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
        return obj.parent.name;
    } else {
        return obj.name;
    }
}

// whenClicked puzzle
function registerOnClick(objSelector, xRay, doubleClick, mouseButtons, cbDo, cbIfMissedDo) {

    // for AR/VR
    _pGlob.objClickInfo = _pGlob.objClickInfo || [];

    _pGlob.objClickInfo.push({
        objSelector: objSelector,
        callbacks: [cbDo, cbIfMissedDo]
    });

    initObjectPicking(function(intersects, event) {

        var isPicked = false;

        var maxIntersects = xRay ? intersects.length : Math.min(1, intersects.length);

        for (var i = 0; i < maxIntersects; i++) {
            var obj = intersects[i].object;
            var objName = getPickedObjectName(obj);
            var objNames = retrieveObjectNames(objSelector);

            if (objectsIncludeObj(objNames, objName)) {
                // save the object for the pickedObject block
                _pGlob.pickedObject = objName;
                isPicked = true;
                cbDo(event);
            }
        }

        if (!isPicked) {
            _pGlob.pickedObject = '';
            cbIfMissedDo(event);
        }

    }, doubleClick ? 'dblclick' : 'mousedown', false, mouseButtons);
}

_pGlob.animMixerCallbacks = [];

var initAnimationMixer = function() {

    function onMixerFinished(e) {
        var cb = _pGlob.animMixerCallbacks;
        var found = [];
        for (var i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (var i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished)) {
            bindListener(appInstance.mixer, 'finished', onMixerFinished);
        }
    };

}();

// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;
        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();
                if (loop && (loop != "AUTO"))
                    action.loop = v3d[loop];
                var scene = getSceneByAction(action);
                var frameRate = getSceneAnimFrameRate(scene);

                action.repetitions = Infinity;

                var timeScale = Math.abs(parseFloat(speed));
                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                var callbacks = _pGlob.animMixerCallbacks;
                var found = false;

                for (var j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            var callbacks = _pGlob.animMixerCallbacks;
            for (var j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            var scene = getSceneByAction(action);
            var frameRate = getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        case 'SET_SPEED':
            var timeScale = parseFloat(speed);
            action.timeScale = rev ? -timeScale : timeScale;
            break;
        }
    }

    for (var i = 0; i < animations.length; i++) {
        var animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}

// Describe this function...
function stopnotclicked() {
  stopclicked = 'Faux';
}

// Describe this function...
function rothorclicked2() {
  rothorclicked = 'Vrai';
  rotantihorclicked = 'Faux';

  operateAnimation('SET_SPEED', 'Armature', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Axe', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Barillet', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'BRep_1.001', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'BRep_1.002', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'BRep_1.003', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'BRep_1.004', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'BRep_1.005', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'BRep_1.006', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'BRep_1.007', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Doigt-1', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Doigt-2', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Doigt-3', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Doigt-4', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Doigt-5', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Doigt-6', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Doigt-7', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Roulement-1', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('SET_SPEED', 'Roulement-2', null, null, 'AUTO', 2,
          function() {}, true);


  operateAnimation('RESUME', 'Armature', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Axe', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Barillet', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.001', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.002', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.003', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.004', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.005', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.006', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.007', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-2', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-3', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-4', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-5', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-6', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-7', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Roulement-1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Roulement-2', null, null, 'AUTO', 1,
          function() {}, false);

      }

// Describe this function...
function rothornotclicked() {
  rothorclicked = 'Faux';
}

// Describe this function...
function rotantihorclicked2() {
  rotantihorclicked = 'Vrai';
  rothorclicked = 'Faux';

  operateAnimation('SET_SPEED', 'Armature', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Axe', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Barillet', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'BRep_1.001', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'BRep_1.002', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'BRep_1.003', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'BRep_1.004', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'BRep_1.005', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'BRep_1.006', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'BRep_1.007', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Doigt-1', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Doigt-2', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Doigt-3', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Doigt-4', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Doigt-5', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Doigt-6', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Doigt-7', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Roulement-1', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('SET_SPEED', 'Roulement-2', null, null, 'AUTO', 2,
          function() {}, false);


  operateAnimation('RESUME', 'Armature', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Axe', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Barillet', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.001', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.002', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.003', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.004', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.005', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.006', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'BRep_1.007', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-2', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-3', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-4', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-5', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-6', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Doigt-7', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Roulement-1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('RESUME', 'Roulement-2', null, null, 'AUTO', 1,
          function() {}, false);

      }

// Describe this function...
function rotantihornotclicked() {
  rotantihorclicked = 'Faux';
}

// Describe this function...
function stopclicked2() {
  stopclicked = 'Vrai';

  operateAnimation('PAUSE', 'Armature', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Axe', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Barillet', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'BRep_1.001', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'BRep_1.002', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'BRep_1.003', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'BRep_1.004', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'BRep_1.005', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'BRep_1.006', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'BRep_1.007', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Doigt-1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Doigt-2', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Doigt-3', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Doigt-4', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Doigt-5', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Doigt-6', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Doigt-7', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Roulement-1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PAUSE', 'Roulement-2', null, null, 'AUTO', 1,
          function() {}, false);

      }


registerEveryFrame(function() {
  if (rotantihorclicked == 'Vrai') {
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 187) {
      assignMat('BRep_1.001', 'Green_trans');
      assignMat('BRep_1.010', 'Green');
    }
    if (getAnimationFrame('Armature') >= 188 && getAnimationFrame('Armature') <= 351) {
      assignMat('BRep_1.001', 'Red_trans');
      assignMat('BRep_1.010', 'Red');
    }
    if (getAnimationFrame('Armature') >= 352 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.001', 'Green_trans');
      assignMat('BRep_1.010', 'Green');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 137) {
      assignMat('BRep_1.002', 'Green_trans');
      assignMat('BRep_1.011', 'Green');
    }
    if (getAnimationFrame('Armature') >= 138 && getAnimationFrame('Armature') <= 300) {
      assignMat('BRep_1.002', 'Red_trans');
      assignMat('BRep_1.011', 'Red');
    }
    if (getAnimationFrame('Armature') >= 301 && getAnimationFrame('Armature') <= 318) {
      assignMat('BRep_1.002', 'Green_trans');
      assignMat('BRep_1.011', 'Green');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 87) {
      assignMat('BRep_1.003', 'Green_trans');
      assignMat('BRep_1.012', 'Green');
    }
    if (getAnimationFrame('Armature') >= 88 && getAnimationFrame('Armature') <= 247) {
      assignMat('BRep_1.003', 'Red_trans');
      assignMat('BRep_1.012', 'Red');
    }
    if (getAnimationFrame('Armature') >= 248 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.003', 'Green_trans');
      assignMat('BRep_1.012', 'Green');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 35) {
      assignMat('BRep_1.004', 'Green_trans');
      assignMat('BRep_1.013', 'Green');
    }
    if (getAnimationFrame('Armature') >= 36 && getAnimationFrame('Armature') <= 197) {
      assignMat('BRep_1.004', 'Red_trans');
      assignMat('BRep_1.013', 'Red');
    }
    if (getAnimationFrame('Armature') >= 198 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.004', 'Green_trans');
      assignMat('BRep_1.013', 'Green');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 146) {
      assignMat('BRep_1.005', 'Red_trans');
      assignMat('BRep_1.014', 'Red');
    }
    if (getAnimationFrame('Armature') >= 147 && getAnimationFrame('Armature') <= 343) {
      assignMat('BRep_1.005', 'Green_trans');
      assignMat('BRep_1.014', 'Green');
    }
    if (getAnimationFrame('Armature') >= 344 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.005', 'Red_trans');
      assignMat('BRep_1.014', 'Red');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 93) {
      assignMat('BRep_1.006', 'Red_trans');
      assignMat('BRep_1.015', 'Red');
    }
    if (getAnimationFrame('Armature') >= 94 && getAnimationFrame('Armature') <= 291) {
      assignMat('BRep_1.006', 'Green_trans');
      assignMat('BRep_1.015', 'Green');
    }
    if (getAnimationFrame('Armature') >= 292 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.006', 'Red_trans');
      assignMat('BRep_1.015', 'Red');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 43) {
      assignMat('BRep_1.007', 'Red_trans');
      assignMat('BRep_1.016', 'Red');
    }
    if (getAnimationFrame('Armature') >= 44 && getAnimationFrame('Armature') <= 241) {
      assignMat('BRep_1.007', 'Green_trans');
      assignMat('BRep_1.016', 'Green');
    }
    if (getAnimationFrame('Armature') >= 242 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.007', 'Red_trans');
      assignMat('BRep_1.016', 'Red');
    }
    if (isAnimationPlaying('Armature')) {
      assignMat('BRep_1.008', 'Green_trans');
      assignMat('BRep_1.009', 'Red_trans');
      changeVis('BRep_1.164', true);
      changeVis('BRep_1.165', true);
      assignMat('BRep_1.164', 'Red');
      assignMat('BRep_1.165', 'Green');
      changeVis('BRep_1.163', false);
      changeVis('BRep_1.166', false);
    }
  }
});

registerEveryFrame(function() {
  if (rothorclicked == 'Vrai') {
    if (getAnimationFrame('Armature') >= 6 && getAnimationFrame('Armature') <= 174) {
      assignMat('BRep_1.001', 'Red_trans');
      assignMat('BRep_1.010', 'Red');
    } else {
      assignMat('BRep_1.001', 'Green_trans');
      assignMat('BRep_1.010', 'Green');
    }
    if (getAnimationFrame('Armature') >= 120 && getAnimationFrame('Armature') <= 316) {
      assignMat('BRep_1.002', 'Green_trans');
      assignMat('BRep_1.011', 'Green');
    } else {
      assignMat('BRep_1.002', 'Red_trans');
      assignMat('BRep_1.011', 'Red');
    }
    if (getAnimationFrame('Armature') >= 69 && getAnimationFrame('Armature') <= 266) {
      assignMat('BRep_1.003', 'Green_trans');
      assignMat('BRep_1.012', 'Green');
    } else {
      assignMat('BRep_1.003', 'Red_trans');
      assignMat('BRep_1.012', 'Red');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 15) {
      assignMat('BRep_1.004', 'Red_trans');
      assignMat('BRep_1.013', 'Red');
    }
    if (getAnimationFrame('Armature') >= 16 && getAnimationFrame('Armature') <= 216) {
      assignMat('BRep_1.004', 'Green_trans');
      assignMat('BRep_1.013', 'Green');
    }
    if (getAnimationFrame('Armature') >= 217 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.004', 'Red_trans');
      assignMat('BRep_1.013', 'Red');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 164) {
      assignMat('BRep_1.005', 'Green_trans');
      assignMat('BRep_1.014', 'Green');
    }
    if (getAnimationFrame('Armature') >= 165 && getAnimationFrame('Armature') <= 324) {
      assignMat('BRep_1.005', 'Red_trans');
      assignMat('BRep_1.014', 'Red');
    }
    if (getAnimationFrame('Armature') >= 325 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.005', 'Green_trans');
      assignMat('BRep_1.014', 'Green');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 111) {
      assignMat('BRep_1.006', 'Green_trans');
      assignMat('BRep_1.015', 'Green');
    }
    if (getAnimationFrame('Armature') >= 112 && getAnimationFrame('Armature') <= 273) {
      assignMat('BRep_1.006', 'Red_trans');
      assignMat('BRep_1.015', 'Red');
    }
    if (getAnimationFrame('Armature') >= 274 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.006', 'Green_trans');
      assignMat('BRep_1.015', 'Green');
    }
    if (getAnimationFrame('Armature') >= 0 && getAnimationFrame('Armature') <= 60) {
      assignMat('BRep_1.007', 'Green_trans');
      assignMat('BRep_1.016', 'Green');
    }
    if (getAnimationFrame('Armature') >= 61 && getAnimationFrame('Armature') <= 221) {
      assignMat('BRep_1.007', 'Red_trans');
      assignMat('BRep_1.016', 'Red');
    }
    if (getAnimationFrame('Armature') >= 222 && getAnimationFrame('Armature') <= 359) {
      assignMat('BRep_1.007', 'Green_trans');
      assignMat('BRep_1.016', 'Green');
    }
    if (isAnimationPlaying('Armature')) {
      assignMat('BRep_1.008', 'Red_trans');
      assignMat('BRep_1.009', 'Green_trans');
      changeVis('BRep_1.163', true);
      changeVis('BRep_1.166', true);
      assignMat('BRep_1.163', 'Red');
      assignMat('BRep_1.166', 'Green');
      changeVis('BRep_1.164', false);
      changeVis('BRep_1.165', false);
    }
  }
});

stopclicked = 'Vrai';

registerEveryFrame(function() {
  if (stopclicked == 'Vrai') {
    assignMat('BRep_1.010', 'Blue_trans');
    assignMat('BRep_1.011', 'Blue_trans');
    assignMat('BRep_1.012', 'Blue_trans');
    assignMat('BRep_1.013', 'Blue_trans');
    assignMat('BRep_1.014', 'Blue_trans');
    assignMat('BRep_1.015', 'Blue_trans');
    assignMat('BRep_1.016', 'Blue_trans');
    assignMat('BRep_1.008', 'Blue_trans');
    assignMat('BRep_1.009', 'Blue_trans');
    changeVis('BRep_1.163', false);
    changeVis('BRep_1.164', false);
    changeVis('BRep_1.165', false);
    changeVis('BRep_1.166', false);
  }
});

registerOnClick('Empty', false, false, [0,1,2], function() {
  if (rothorclicked == 'Faux') {
    rothorclicked2();
    getJSFunction('passvariablerothorclicked')();
    rotantihornotclicked();
    getJSFunction('passvariablerotantihornotclicked')();
    stopnotclicked();
    getJSFunction('passvariablestopnotclicked')();
  }
  if (rotantihorclicked == 'Faux') {
    rotantihorclicked2();
    getJSFunction('passvariablerotantihorclicked')();
    rothornotclicked();
    getJSFunction('passvariablerothornotclicked')();
    stopnotclicked();
    getJSFunction('passvariablestopnotclicked')();
  }
  if (stopclicked == 'Faux') {
    rotantihornotclicked();
    getJSFunction('passvariablerotantihornotclicked')();
    rothornotclicked();
    getJSFunction('passvariablerothornotclicked')();
    stopclicked2();
    getJSFunction('passvariablestopclicked')();
  }
}, function() {});

changeVis('BRep_1.001', false);
changeVis('BRep_1.002', false);
changeVis('BRep_1.003', false);
changeVis('BRep_1.004', false);
changeVis('BRep_1.005', false);
changeVis('BRep_1.006', false);
changeVis('BRep_1.007', false);


operateAnimation('PAUSE', 'Armature', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Axe', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Barillet', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'BRep_1.001', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'BRep_1.002', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'BRep_1.003', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'BRep_1.004', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'BRep_1.005', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'BRep_1.006', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'BRep_1.007', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Doigt-1', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Doigt-2', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Doigt-3', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Doigt-4', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Doigt-5', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Doigt-6', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Doigt-7', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Roulement-1', null, null, 'AUTO', 1,
        function() {}, false);


operateAnimation('PAUSE', 'Roulement-2', null, null, 'AUTO', 1,
        function() {}, false);



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
